// Generated by CoffeeScript 1.7.1
(function() {
  var Antenna, dashedArc;

  (typeof exports !== "undefined" && exports !== null ? exports : this).Antennas = [];

  dashedArc = function(ctx, radius, dash, start, stop) {
    var theta, _i, _ref;
    ctx.beginPath();
    for (theta = _i = start, _ref = dash * 2; _ref > 0 ? _i <= stop : _i >= stop; theta = _i += _ref) {
      ctx.moveTo(Math.cos(theta) * radius, Math.sin(theta) * radius);
      ctx.lineTo(Math.cos(theta + dash) * radius, Math.sin(theta + dash) * radius);
    }
  };

  Antenna = (function() {
    function Antenna(name, range, energy, angle) {
      this.name = name;
      this.range = range;
      this.energy = energy;
      this.angle = angle;
      if (angle != null) {
        this.angle = this.angle * (Math.PI / 180);
      }
    }

    Antenna.prototype.isOmni = function() {
      return !this.isDish();
    };

    Antenna.prototype.isDish = function() {
      return this.angle != null;
    };

    Antenna.prototype.drawRange = function(ctx) {
      ctx.save();
      ctx.strokeStyle = "#AAAAAA";
      if (this.isDish()) {

      } else {
        dashedArc(ctx, s(this.range), 0.1, 0, Math.PI * 2);
        ctx.stroke();
      }
      return ctx.restore();
    };

    return Antenna;

  })();

  Antennas.push(new Antenna("Reflectron DP-10", 500.0e3, 0.01));

  Antennas.push(new Antenna("Communotron 16", 2.500e6, 0.13));

  Antennas.push(new Antenna("CommTech EXP-VR-2T", 3.0e6, 0.18));

  Antennas.push(new Antenna("Communotron 32", 5.0e6, 0.60));

}).call(this);
